# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Présentation"
  url = "#hero"
  weight = 10

[[main]]
  name = "Événements"
  url = "#events"
  weight = 20

[[main]]
  name = "Éthique"
  url = "/conduite"
  weight = 30

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

[[main_right]]
  name = "<span class=\"fab fa-github\" style=\"font-size: 1rem; line-height: 1.25\"></span>"
  post = ""
  url = "https://github.com/ComputArcheo"
  weight = 10
