# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Accueil"
  url = "#hero"
  weight = 10

[[main]]
  name = "Agenda"
  url = "#talks"
  weight = 20

[[main]]
  name = "Fonctionnement"
  url = "/about"
  weight = 30

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60
